=== Wredter/XML-e/xml/plajlisty.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="stringtype">
  <xs:restriction base="xs:string"/>
</xs:simpleType>

<xs:simpleType name="inttype">
  <xs:restriction base="xs:integer"/>
</xs:simpleType>

<xs:simpleType name="date">
  <xs:restriction base="xs:date"/>
</xs:simpleType>

<xs:simpleType name="czas">
<xs:restriction base="xs:string">
<xs:pattern value="[0-9]{1,2}:[0-5]{1}[0-9]{1}"/>
</xs:restriction>
</xs:simpleType>

  <xs:simpleType name="indeks">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="100000"/>
      <xs:maxInclusive value="999999"/>
    </xs:restriction>
  </xs:simpleType>

 <xs:complexType name="rootType">
  <xs:sequence>
   <xs:element name="metadane" type="metadaneType" maxOccurs="1" />
   <xs:element name="lista_gatunkow" type="lista_gatunkowType" maxOccurs="1" />
   <xs:element name="lista_wykonawcow" type="lista_wykonawcowType" maxOccurs="1" />
   <xs:element name="lista_piosenek" type="lista_piosenekType" maxOccurs="1" />
   <xs:element name="plajlista" type="plajlistaType" maxOccurs="unbounded" />
  </xs:sequence>
 </xs:complexType>

 
  <xs:complexType name="metadaneType">
  <xs:sequence>
   <xs:element name="autor" minOccurs="1" maxOccurs="2" type="autorType" />
   <xs:element name="data_modyfikacji" minOccurs="1" maxOccurs="1" type="date" />
  </xs:sequence>
 </xs:complexType>
 
  <xs:group name="autorGroup">
<xs:sequence>
   <xs:element name="imie" minOccurs="1" maxOccurs="1" type="stringtype" />
   <xs:element name="nazwisko" minOccurs="1" maxOccurs="1" type="stringtype" />
   <xs:element name="nr_indeksu" minOccurs="1" maxOccurs="1" type="indeks" />
  </xs:sequence>
</xs:group>
 
 <xs:complexType name="autorType">
	<xs:group ref="autorGroup"/>
 </xs:complexType>
 
  <xs:complexType name="lista_gatunkowType">
  <xs:sequence>
   <xs:element name="gatunek" maxOccurs="unbounded" type="gatunekType" />
  </xs:sequence>
 </xs:complexType>
 
    <xs:complexType name="gatunekType">
      <xs:simpleContent>
        <xs:extension base="stringtype">
          <xs:attribute name="id" type="stringtype" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>

  <xs:complexType name="lista_wykonawcowType">
  <xs:sequence>
   <xs:element name="wykonawca" maxOccurs="unbounded" type="wykonawcaType" />
  </xs:sequence>
 </xs:complexType>
 
    <xs:attributeGroup name="wykonawcaAtrrGroup">
      <xs:attribute name="id" type="stringtype" use="required" />
  <xs:attribute name="nazwa" type="stringtype" use="required" />
  </xs:attributeGroup>
 
   <xs:complexType name="wykonawcaType">
  <xs:sequence>
   <xs:element name="artysta" maxOccurs="unbounded" type="artystaType" />
  </xs:sequence>
  <xs:attributeGroup ref = "wykonawcaAtrrGroup"/>
 </xs:complexType>
 
    <xs:complexType name="artystaType">
  <xs:sequence>
   <xs:element name="imie" maxOccurs="1" type="stringtype" />
   <xs:element name="nazwisko" maxOccurs="1" type="stringtype" />
  </xs:sequence>
  <xs:attribute name="pseudo" type="stringtype" />
 </xs:complexType>
 
     <xs:complexType name="lista_piosenekType">
  <xs:sequence>
   <xs:element name="piosenka" maxOccurs="unbounded" type="piosenkaType" />
  </xs:sequence>
 </xs:complexType>
 
   <xs:attributeGroup name="piosenkaAtrrGroup">
    <xs:attribute name="tytul" type="stringtype" />
        <xs:attribute default="niezidentyfikowana" name="nastroj">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="smutna" />
            <xs:enumeration value="wesola" />
            <xs:enumeration value="mieszana" />
            <xs:enumeration value="niezidentyfikowana" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
  <xs:attribute name="gatunek" type="stringtype" use="required" />
  <xs:attribute name="wykonawca" type="stringtype" use="required" />
  </xs:attributeGroup>
 
      <xs:complexType name="piosenkaType">
  <xs:sequence>
   <xs:element name="czas_trwania" maxOccurs="1" type="czas" />
   <xs:element name="album" maxOccurs="1" type="stringtype" />
   <xs:element name="rok_wydania" maxOccurs="1" type="inttype" />
  </xs:sequence>
  <xs:attributeGroup ref = "piosenkaAtrrGroup"/>
 </xs:complexType>
 
	<xs:complexType name="plajlistaType">
  <xs:sequence>
   <xs:element name="piosenkaRef" maxOccurs="unbounded" type="piosenkaReferenceType" />
  </xs:sequence>
  <xs:attribute name="nazwa" type="stringtype" />
 </xs:complexType>
 
     <xs:complexType name="piosenkaReferenceType">
          <xs:attribute name="tytulRef" type="stringtype" use="required" />
    </xs:complexType>



<xs:element name="root" type="rootType">
   <xs:key name="piosenkaKey">
  <xs:selector xpath="lista_piosenek/piosenka" />
  <xs:field xpath="@tytul" />
 </xs:key>
 
 <xs:keyref name="piosenkaKeyRef" refer="piosenkaKey">
  <xs:selector xpath="plajlista/piosenkaRef" />
  <xs:field xpath="@tytulRef" />
 </xs:keyref>
 
    <xs:key name="gatunekKey">
  <xs:selector xpath="lista_gatunkow/gatunek" />
  <xs:field xpath="@id" />
 </xs:key>
 
 <xs:keyref name="gatunekKeyRef" refer="gatunekKey">
  <xs:selector xpath="lista_piosenek/piosenka" />
  <xs:field xpath="@gatunek" />
   </xs:keyref>
  
      <xs:key name="wykonawcaKey">
  <xs:selector xpath="lista_wykonawcow/wykonawca" />
  <xs:field xpath="@id" />
 </xs:key>
 
 <xs:keyref name="wykonawcaKeyRef" refer="wykonawcaKey">
  <xs:selector xpath="lista_piosenek/piosenka" />
  <xs:field xpath="@wykonawca" />
 </xs:keyref>
</xs:element>
</xs:schema>

=== Wredter/XML-e/xml/nowy.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plajlisty.xsd"><metadane><autor><imie>Wiktor</imie><nazwisko>Muraszko</nazwisko><nr_indeksu>210281</nr_indeksu></autor><autor><imie>Wojciech</imie><nazwisko>Mosieński</nazwisko><nr_indeksu>210280</nr_indeksu></autor><data_modyfikacji>2019-03-29</data_modyfikacji></metadane><lista_gatunkow><gatunek id="Rock">Rock</gatunek><gatunek id="Pop">Pop</gatunek><gatunek id="Alternatywna">Alternatywna</gatunek><gatunek id="eloasd">ddddddd</gatunek></lista_gatunkow><lista_wykonawcow><wykonawca id="GNR" nazwa="Guns N’ Rosesdsadsa"><artysta><imie>Axldd</imie><nazwisko>Rosedd</nazwisko></artysta><artysta pseudo="Slashaa"><imie>Souldd</imie><nazwisko>Hudsondd</nazwisko></artysta><artysta pseudo="asd"><imie>Izzy</imie><nazwisko>Stradlin</nazwisko></artysta></wykonawca><wykonawca id="MT" nazwa="Modern Talkingddddd"><artysta><imie>Dieter</imie><nazwisko>Bohlen</nazwisko></artysta><artysta><imie>Thomas</imie><nazwisko>Anders</nazwisko></artysta></wykonawca><wykonawca id="qwe" nazwa="ewq"><artysta pseudo=""><imie>q1</imie><nazwisko>w2</nazwisko></artysta><artysta pseudo=""><imie>elo</imie><nazwisko>sd</nazwisko></artysta></wykonawca></lista_wykonawcow><lista_piosenek><piosenka tytul="It's So Easyfdsafdsaf" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:23</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Nighttrain" nastroj="mieszana" gatunek="Alternatywna" wykonawca="MT"><czas_trwania>4:29</czas_trwania><album>Appetite for Destructionddddddd</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Out Ta Get Me" nastroj="mieszana" gatunek="Rock" wykonawca="GNR"><czas_trwania>4:25</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1233</rok_wydania></piosenka><piosenka tytul="Mr. Brownstone" nastroj="smutna" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:49</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Paradise City" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>6:46</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="My Michelle" nastroj="niezidentyfikowana" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:40</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Think About You" nastroj="smutna" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:52</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Sweet Child O' Mine" nastroj="smutna" gatunek="Rock" wykonawca="GNR"><czas_trwania>5:55</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="You're Crazy" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:17</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Anything Goes" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:26</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Rocet Queen" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:40</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Brother Louie" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:41</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Just We Two" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:54</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Lady Lai" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>4:55</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Doctor for My Heart" nastroj="niezidentyfikowana" gatunek="Pop" wykonawca="MT"><czas_trwania>3:16</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Save Me - Don't Break Me" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:45</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Atlantis Is Calling" nastroj="niezidentyfikowana" gatunek="Pop" wykonawca="MT"><czas_trwania>3:48</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Keep Lova Alive" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:25</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Hey You" nastroj="niezidentyfikowana" gatunek="Pop" wykonawca="MT"><czas_trwania>3:20</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Angie's Heart" nastroj="mieszana" gatunek="Pop" wykonawca="MT"><czas_trwania>3:37</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Only Love Can Break My Heart" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:35</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="asfdsafdsaf" nastroj="mieszana" gatunek="eloasd" wykonawca="qwe"><czas_trwania>4:29</czas_trwania><album>Appetite for Destructionddddddd</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="asfdselo" nastroj="niezidentyfikowana" gatunek="eloasd" wykonawca="qwe"><czas_trwania>4:29</czas_trwania><album>Adasd</album><rok_wydania>1987</rok_wydania></piosenka></lista_piosenek><plajlista nazwa="Guns'i A4Dddddddd"><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Paradise City"/><piosenkaRef tytulRef="My Michelle"/><piosenkaRef tytulRef="Think About You"/><piosenkaRef tytulRef="Sweet Child O' Mine"/><piosenkaRef tytulRef="You're Crazy"/><piosenkaRef tytulRef="Anything Goes"/><piosenkaRef tytulRef="Rocet Queen"/></plajlista><plajlista nazwa="Eternal Romance"><piosenkaRef tytulRef="Brother Louie"/><piosenkaRef tytulRef="Just We Two"/><piosenkaRef tytulRef="Lady Lai"/><piosenkaRef tytulRef="Doctor for My Heart"/><piosenkaRef tytulRef="Save Me - Don't Break Me"/><piosenkaRef tytulRef="Atlantis Is Calling"/><piosenkaRef tytulRef="Keep Lova Alive"/><piosenkaRef tytulRef="Hey You"/><piosenkaRef tytulRef="Angie's Heart"/><piosenkaRef tytulRef="Only Love Can Break My Heart"/></plajlista><plajlista nazwa="elo"><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="asfdsafdsaf"/><piosenkaRef tytulRef="asfdselo"/></plajlista></root>

=== Wredter/XML-e/xml/elo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plajlisty.xsd"><metadane><autor><imie>Wiktor</imie><nazwisko>Muraszko</nazwisko><nr_indeksu>210281</nr_indeksu></autor><autor><imie>Wojciech</imie><nazwisko>Mosieński</nazwisko><nr_indeksu>210280</nr_indeksu></autor><data_modyfikacji>2019-03-29</data_modyfikacji></metadane><lista_gatunkow><gatunek id="Rock">Rock</gatunek><gatunek id="Pop">Pop</gatunek><gatunek id="Alternatywna">Alternatywna</gatunek></lista_gatunkow><lista_wykonawcow><wykonawca id="GNR" nazwa="Guns N’ Roses"><artysta><imie>Axl</imie><nazwisko>Rose</nazwisko></artysta><artysta pseudo="Slash"><imie>Soul</imie><nazwisko>Hudson</nazwisko></artysta><artysta><imie>Izzy</imie><nazwisko>Stradlin</nazwisko></artysta><artysta><imie>Duff</imie><nazwisko>McKagan</nazwisko></artysta><artysta><imie>Steven</imie><nazwisko>Adler</nazwisko></artysta></wykonawca><wykonawca id="MT" nazwa="Modern Talking"><artysta><imie>Dieter</imie><nazwisko>Bohlen</nazwisko></artysta><artysta><imie>Thomas</imie><nazwisko>Anders</nazwisko></artysta></wykonawca></lista_wykonawcow><lista_piosenek><piosenka tytul="It's So Easy" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:23</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Nighttrain" nastroj="smutna" gatunek="Rock" wykonawca="GNR"><czas_trwania>4:29</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Out Ta Get Me" nastroj="mieszana" gatunek="Rock" wykonawca="GNR"><czas_trwania>4:25</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Mr. Brownstone" nastroj="smutna" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:49</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Paradise City" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>6:46</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="My Michelle" nastroj="niezidentyfikowana" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:40</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Think About You" nastroj="smutna" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:52</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Sweet Child O' Mine" nastroj="smutna" gatunek="Rock" wykonawca="GNR"><czas_trwania>5:55</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="You're Crazy" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:17</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Anything Goes" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:26</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Rocet Queen" nastroj="wesola" gatunek="Rock" wykonawca="GNR"><czas_trwania>3:40</czas_trwania><album>Appetite for Destruction</album><rok_wydania>1987</rok_wydania></piosenka><piosenka tytul="Brother Louie" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:41</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Just We Two" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:54</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Lady Lai" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>4:55</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Doctor for My Heart" nastroj="niezidentyfikowana" gatunek="Pop" wykonawca="MT"><czas_trwania>3:16</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Save Me - Don't Break Me" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:45</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Atlantis Is Calling" nastroj="niezidentyfikowana" gatunek="Pop" wykonawca="MT"><czas_trwania>3:48</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Keep Lova Alive" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:25</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Hey You" nastroj="niezidentyfikowana" gatunek="Pop" wykonawca="MT"><czas_trwania>3:20</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Angie's Heart" nastroj="mieszana" gatunek="Pop" wykonawca="MT"><czas_trwania>3:37</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka><piosenka tytul="Only Love Can Break My Heart" nastroj="smutna" gatunek="Pop" wykonawca="MT"><czas_trwania>3:35</czas_trwania><album>Ready for Romance</album><rok_wydania>1986</rok_wydania></piosenka></lista_piosenek><plajlista nazwa="Guns'i A4D"><piosenkaRef tytulRef="It's So Easy"/><piosenkaRef tytulRef="Nighttrain"/><piosenkaRef tytulRef="Out Ta Get Me"/><piosenkaRef tytulRef="Mr. Brownstone"/><piosenkaRef tytulRef="Paradise City"/><piosenkaRef tytulRef="My Michelle"/><piosenkaRef tytulRef="Think About You"/><piosenkaRef tytulRef="Sweet Child O' Mine"/><piosenkaRef tytulRef="You're Crazy"/><piosenkaRef tytulRef="Anything Goes"/><piosenkaRef tytulRef="Rocet Queen"/></plajlista><plajlista nazwa="Eternal Romance"><piosenkaRef tytulRef="Brother Louie"/><piosenkaRef tytulRef="Just We Two"/><piosenkaRef tytulRef="Lady Lai"/><piosenkaRef tytulRef="Doctor for My Heart"/><piosenkaRef tytulRef="Save Me - Don't Break Me"/><piosenkaRef tytulRef="Atlantis Is Calling"/><piosenkaRef tytulRef="Keep Lova Alive"/><piosenkaRef tytulRef="Hey You"/><piosenkaRef tytulRef="Angie's Heart"/><piosenkaRef tytulRef="Only Love Can Break My Heart"/></plajlista></root>

=== Wredter/XML-e/playlisty.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="plajlisty.css" type="text/css" ?>

<root
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="plajlisty.xsd" xsi:schemaLocation="plajlisty.xsd">
 
 <metadane>
        <autor>
            <imie>Wiktor</imie>
            <nazwisko>Muraszko</nazwisko>
            <nr_indeksu>210281</nr_indeksu>
        </autor>
        <autor>
            <imie>Wojciech</imie>
            <nazwisko>Mosieński</nazwisko>
            <nr_indeksu>210280</nr_indeksu>
        </autor>
        <data_modyfikacji>2019-03-29</data_modyfikacji>
    </metadane>
    <lista_gatunków>
        <gatunek id="Rock">Rock</gatunek>
        <gatunek id="Pop">Pop</gatunek>
        <gatunek id="Alternatywna">Alternatywna</gatunek>
    </lista_gatunków>
	<lista_wykonawców>
        <wykonawca id="GNR" nazwa="Guns N’ Roses">
            <artysta><imie>Axl</imie><nazwisko>Rose</nazwisko></artysta>
			<artysta pseudo="Slash"><imie>Soul</imie><nazwisko>Hudson</nazwisko></artysta>
            <artysta><imie>Izzy</imie><nazwisko>Stradlin</nazwisko></artysta>
            <artysta><imie>Duff</imie><nazwisko>McKagan</nazwisko></artysta>
            <artysta><imie>Steven</imie><nazwisko>Adler</nazwisko></artysta>
        </wykonawca>
        <wykonawca id="MT" nazwa="Modern Talking">
			<artysta><imie>Dieter</imie><nazwisko>Bohlen</nazwisko></artysta>
			<artysta><imie>Thomas</imie><nazwisko>Anders</nazwisko></artysta>
        </wykonawca>
    </lista_wykonawców>
	<lista_piosenek>
	    <piosenka tytuł="It's So Easy" wykonawca="GNR" gatunek="Rock" nastrój="wesoła">
            <czas_trwania>3:23</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
		<piosenka tytuł="Nighttrain" wykonawca="GNR" gatunek="Rock" nastrój="smutna">
            <czas_trwania>4:29</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
		<piosenka tytuł="Out Ta Get Me" wykonawca="GNR" gatunek="Rock" nastrój="mieszana">
            <czas_trwania>4:25</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
        <piosenka tytuł="Mr. Brownstone" wykonawca="GNR" gatunek="Rock" nastrój="smutna">
            <czas_trwania>3:49</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
        <piosenka tytuł="Paradise City" wykonawca="GNR" gatunek="Rock" nastrój="wesoła">
            <czas_trwania>6:46</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
        <piosenka tytuł="My Michelle" wykonawca="GNR" gatunek="Rock" nastrój="niezidentyfikowana">
            <czas_trwania>3:40</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
        <piosenka tytuł="Think About You" wykonawca="GNR" gatunek="Rock" nastrój="smutna">
            <czas_trwania>3:52</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
        <piosenka tytuł="Sweet Child O' Mine" wykonawca="GNR" gatunek="Rock" nastrój="smutna">
            <czas_trwania>5:55</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
        <piosenka tytuł="You're Crazy" wykonawca="GNR" gatunek="Rock" nastrój="wesoła">
            <czas_trwania>3:17</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
        <piosenka tytuł="Anything Goes" wykonawca="GNR" gatunek="Rock" nastrój="wesoła">
            <czas_trwania>3:26</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
        <piosenka tytuł="Rocet Queen" wykonawca="GNR" gatunek="Rock" nastrój="wesoła">
            <czas_trwania>3:40</czas_trwania>
            <album>Appetite for Destruction</album>
            <rok_wydania>1987</rok_wydania>
        </piosenka>
		<piosenka tytuł="Brother Louie" wykonawca="MT" gatunek="Pop" nastrój="smutna">
            <czas_trwania>3:41</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
        <piosenka tytuł="Just We Two" wykonawca="MT" gatunek="Pop" nastrój="smutna">
            <czas_trwania>3:54</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
        <piosenka tytuł="Lady Lai" wykonawca="MT" gatunek="Pop" nastrój="smutna">
            <czas_trwania>4:55</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
        <piosenka tytuł="Doctor for My Heart" wykonawca="MT" gatunek="Pop" nastrój="niezidentyfikowana">
            <czas_trwania>3:16</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
        <piosenka tytuł="Save Me - Don't Break Me" wykonawca="MT" gatunek="Pop" nastrój="smutna">
            <czas_trwania>3:45</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
        <piosenka tytuł="Atlantis Is Calling" wykonawca="MT" gatunek="Pop" nastrój="niezidentyfikowana">
            <czas_trwania>3:48</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
        <piosenka tytuł="Keep Lova Alive" wykonawca="MT" gatunek="Pop" nastrój="smutna">
            <czas_trwania>3:25</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
        <piosenka tytuł="Hey You" wykonawca="MT" gatunek="Pop" nastrój="niezidentyfikowana">
            <czas_trwania>3:20</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
        <piosenka tytuł="Angie's Heart" wykonawca="MT" gatunek="Pop" nastrój="mieszana">
            <czas_trwania>3:37</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
        <piosenka tytuł="Only Love Can Break My Heart" wykonawca="MT" gatunek="Pop" nastrój="smutna">
            <czas_trwania>3:35</czas_trwania>
            <album>Ready for Romance</album>
            <rok_wydania>1986</rok_wydania>
        </piosenka>
	</lista_piosenek>
	
	<plajlista nazwa="Guns'i A4D">
		<piosenkaRef tytulRef="It's So Easy" />
		<piosenkaRef tytulRef="Nighttrain" />
		<piosenkaRef tytulRef="Out Ta Get Me" />
		<piosenkaRef tytulRef="Mr. Brownstone" />
		<piosenkaRef tytulRef="Paradise City" />
		<piosenkaRef tytulRef="My Michelle" />
		<piosenkaRef tytulRef="Think About You" />
		<piosenkaRef tytulRef="Sweet Child O' Mine" />
		<piosenkaRef tytulRef="You're Crazy" />
		<piosenkaRef tytulRef="Anything Goes" />
		<piosenkaRef tytulRef="Rocet Queen" />
	</plajlista>
	<plajlista nazwa="Eternal Romance">
		<piosenkaRef tytulRef="Brother Louie" />
		<piosenkaRef tytulRef="Just We Two" />
		<piosenkaRef tytulRef="Lady Lai" />
		<piosenkaRef tytulRef="Doctor for My Heart" />
		<piosenkaRef tytulRef="Save Me - Don't Break Me" />
		<piosenkaRef tytulRef="Atlantis Is Calling" />
		<piosenkaRef tytulRef="Keep Lova Alive" />
		<piosenkaRef tytulRef="Hey You" />
		<piosenkaRef tytulRef="Angie's Heart" />
		<piosenkaRef tytulRef="Only Love Can Break My Heart" />
	</plajlista>
	

 
</root>
